package com.hospital.hospitalapi.service.exception.consts;

public enum ExceptionErrorCodeType {
    LOGIN_ACCOUNT_NOT_FOUND(1000), LOGIN_ACCOUNT_WRONG_PASSWORD(1001), REGISTER_EMAIL_ALREADY_EXISTS(1002),
    REGISTER_AUTHORITY_NOT_FOUND(1003), REGISTER_ACCOUNT_NOT_SAVED(1004), ACTIVATE_ACCOUNT_NOT_FOUND(1005),
    ACTIVATE_ACCOUNT_NOT_SAVED(1006), ACCOUNT_ALREADY_ACTIVATED(1007), FORGOT_PASSWORD_ACCOUNT_NOT_FOUND(1008),
    RESET_PASSWORD_ACCOUNT_NOT_FOUND(1009), RESET_PASSWORD_ACCOUT_NOT_SAVED(1010),
    CHANGE_PASSWORD_ACCOUNT_NOT_FOUND(1011), CHANGE_PASSWORD_NOT_MATCH(1012), CHANGE_PASSWORD_ACCOUNT_NOT_SAVED(1013),
    EMAIL_NOT_SENT(1014), TOKEN_ACCOUNT_INVALID(1015);

    public final int code;

    private ExceptionErrorCodeType(int code) {
        this.code = code;
    }
}
